server:
  port: 80

#首先配置两个数据源
spring:
  datasource:
    master:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/masterdatasource?useSSL=false&serverTimezone=GMT%2B8&characterEncoding=UTF-8
      username: root
      password: root

    slave:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/slavedatasource?useSSL=false&serverTimezone=GMT%2B8&characterEncoding=UTF-8
      username: root
      password: root

